//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSalesOrderDetails_OBService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mikroportalintegration/services", ConfigurationName="WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OB")]
    public interface SI_SalesOrderDetails_OB
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OBResponse> SI_SalesOrderDetails_OBAsync(WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OBRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_S_MSG
    {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_S_ORDER_STAT
    {
        
        private string sIRA_NOField;
        
        private string sIP_NOField;
        
        private string mUSTERIField;
        
        private string sIP_ONAY_DURUMUField;
        
        private string sIP_KALEMField;
        
        private string mALZEMEField;
        
        private string sAS_NOField;
        
        private string uPKField;
        
        private decimal mIKTARField;
        
        private bool mIKTARFieldSpecified;
        
        private decimal sEVK_MIKTARIField;
        
        private bool sEVK_MIKTARIFieldSpecified;
        
        private decimal fIYATField;
        
        private bool fIYATFieldSpecified;
        
        private string pbField;
        
        private string sIP_DURUMField;
        
        private string cONF_TARIHIField;
        
        private string sEVK_TARIHIField;
        
        private string sEVK_DURUMUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SIRA_NO
        {
            get
            {
                return this.sIRA_NOField;
            }
            set
            {
                this.sIRA_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SIP_NO
        {
            get
            {
                return this.sIP_NOField;
            }
            set
            {
                this.sIP_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MUSTERI
        {
            get
            {
                return this.mUSTERIField;
            }
            set
            {
                this.mUSTERIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SIP_ONAY_DURUMU
        {
            get
            {
                return this.sIP_ONAY_DURUMUField;
            }
            set
            {
                this.sIP_ONAY_DURUMUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SIP_KALEM
        {
            get
            {
                return this.sIP_KALEMField;
            }
            set
            {
                this.sIP_KALEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MALZEME
        {
            get
            {
                return this.mALZEMEField;
            }
            set
            {
                this.mALZEMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SAS_NO
        {
            get
            {
                return this.sAS_NOField;
            }
            set
            {
                this.sAS_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string UPK
        {
            get
            {
                return this.uPKField;
            }
            set
            {
                this.uPKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal MIKTAR
        {
            get
            {
                return this.mIKTARField;
            }
            set
            {
                this.mIKTARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MIKTARSpecified
        {
            get
            {
                return this.mIKTARFieldSpecified;
            }
            set
            {
                this.mIKTARFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal SEVK_MIKTARI
        {
            get
            {
                return this.sEVK_MIKTARIField;
            }
            set
            {
                this.sEVK_MIKTARIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SEVK_MIKTARISpecified
        {
            get
            {
                return this.sEVK_MIKTARIFieldSpecified;
            }
            set
            {
                this.sEVK_MIKTARIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal FIYAT
        {
            get
            {
                return this.fIYATField;
            }
            set
            {
                this.fIYATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FIYATSpecified
        {
            get
            {
                return this.fIYATFieldSpecified;
            }
            set
            {
                this.fIYATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PB
        {
            get
            {
                return this.pbField;
            }
            set
            {
                this.pbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SIP_DURUM
        {
            get
            {
                return this.sIP_DURUMField;
            }
            set
            {
                this.sIP_DURUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CONF_TARIHI
        {
            get
            {
                return this.cONF_TARIHIField;
            }
            set
            {
                this.cONF_TARIHIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SEVK_TARIHI
        {
            get
            {
                return this.sEVK_TARIHIField;
            }
            set
            {
                this.sEVK_TARIHIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SEVK_DURUMU
        {
            get
            {
                return this.sEVK_DURUMUField;
            }
            set
            {
                this.sEVK_DURUMUField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_FM_ORDER_STAT", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_SalesOrderDetails_OBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BASL_TRH;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BITS_TRH;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_MUSTERI;
        
        public SI_SalesOrderDetails_OBRequest()
        {
        }
        
        public SI_SalesOrderDetails_OBRequest(string IV_BASL_TRH, string IV_BITS_TRH, string IV_MUSTERI)
        {
            this.IV_BASL_TRH = IV_BASL_TRH;
            this.IV_BITS_TRH = IV_BITS_TRH;
            this.IV_MUSTERI = IV_MUSTERI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_FM_ORDER_STAT.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_SalesOrderDetails_OBResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsSalesOrderDetails_OBService.ZSD_S_MSG ES_MSG;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WsSalesOrderDetails_OBService.ZSD_S_ORDER_STAT[] ET_DATA;
        
        public SI_SalesOrderDetails_OBResponse()
        {
        }
        
        public SI_SalesOrderDetails_OBResponse(WsSalesOrderDetails_OBService.ZSD_S_MSG ES_MSG, WsSalesOrderDetails_OBService.ZSD_S_ORDER_STAT[] ET_DATA)
        {
            this.ES_MSG = ES_MSG;
            this.ET_DATA = ET_DATA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SI_SalesOrderDetails_OBChannel : WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OB, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SI_SalesOrderDetails_OBClient : System.ServiceModel.ClientBase<WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OB>, WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OB
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_SalesOrderDetails_OBClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_SalesOrderDetails_OBClient.GetBindingForEndpoint(endpointConfiguration), SI_SalesOrderDetails_OBClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SalesOrderDetails_OBClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_SalesOrderDetails_OBClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SalesOrderDetails_OBClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_SalesOrderDetails_OBClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SalesOrderDetails_OBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OBResponse> SI_SalesOrderDetails_OBAsync(WsSalesOrderDetails_OBService.SI_SalesOrderDetails_OBRequest request)
        {
            return base.Channel.SI_SalesOrderDetails_OBAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://mkrppod01.mikroportal.com:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
                        "senderService=BC_MIKROPORTAL&receiverParty=&receiverService=&interface=SI_SalesO" +
                        "rderDetails_OB&interfaceNamespace=http%3A%2F%2Fmikroportalintegration%2Fservices" +
                        "");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://mkrppod01.mikroportal.com:50001/XISOAPAdapter/MessageServlet?senderParty=" +
                        "&senderService=BC_MIKROPORTAL&receiverParty=&receiverService=&interface=SI_Sales" +
                        "OrderDetails_OB&interfaceNamespace=http%3A%2F%2Fmikroportalintegration%2Fservice" +
                        "s");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
